import type { FeatureFlagDefinition } from "./types.ts";

export const FEATURE_FLAGS = [
  {
    key: "sales.leads",
    label: "Lead intake",
    group: "Pre-construction",
    description: "Marketing consultation leads, lead assignment and lead management.",
    enabledByDefault: true,
    routePrefixes: ["/leads", "/admin/leads"],
  },
  {
    key: "sales.proposals",
    label: "Proposals & estimates",
    group: "Pre-construction",
    description: "Proposal workspaces, estimates, client proposal links and conversions.",
    enabledByDefault: true,
    routePrefixes: ["/proposals"],
  },
  {
    key: "ai.automatedTakeoff",
    label: "Automated take-off",
    group: "Pre-construction AI",
    description:
      "Drawings-to-BoQ take-off in proposals: automated DWG jobs plus the QS review workspace and proposal BoQ generation.",
    enabledByDefault: true,
    routePrefixes: [
      "/proposals/:id/plans/:planId/automated-takeoff",
      "/proposals/:id/automated-takeoff",
      "/precon",
    ],
  },
  {
    key: "ai.programmeImport",
    label: "Programme import",
    group: "Pre-construction AI",
    description: "Panda AI programme/schedule import from MPP, XML and spreadsheets.",
    enabledByDefault: true,
    routePrefixes: ["/programme-import"],
  },
  {
    key: "ai.projectFileImport",
    label: "Project file extraction",
    group: "Panda AI",
    description: "AI extraction from project files and documents.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/ai/files"],
  },
  {
    key: "ai.insights",
    label: "Panda AI insights",
    group: "Panda AI",
    description: "Project health insights, analysis jobs and AI recommendations.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/ai/insights", "/projects/:id/insights"],
  },
  {
    key: "ai.chatAgent",
    label: "Panda AI chat agent",
    group: "Panda AI",
    description: "Project assistant chat and tool-calling agent.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/ai/agent"],
  },
  {
    key: "projects.documents",
    label: "Documents",
    group: "Project controls",
    description: "Document library, versions, uploads and file shares.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/documents", "/files", "/share"],
  },
  {
    key: "projects.schedule",
    label: "Schedule & activities",
    group: "Project controls",
    description: "Stages, activities, tasks, schedule boards and progress recompute.",
    enabledByDefault: true,
    routePrefixes: [
      "/projects/:id/stages",
      "/projects/:id/activities",
      "/projects/:id/tasks",
      "/projects/:id/look-aheads",
    ],
  },
  {
    key: "projects.multiBuilding",
    label: "Multiple buildings",
    group: "Project controls",
    description:
      "Split a project into multiple buildings that share one funding pool but each run their own programme of work.",
    enabledByDefault: false,
    routePrefixes: ["/projects/:id/buildings"],
  },
  {
    key: "projects.bim",
    label: "BIM coordination",
    group: "Project controls",
    description: "IFC/BIM model upload, issue links and coordination views.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/bim"],
  },
  {
    key: "projects.bimDashboard",
    label: "BIM issue dashboard (preview)",
    group: "Project controls",
    description:
      "Experimental issue-detail dashboard inside the BIM viewer: a flagged element opens a coordination panel with status, due date and location. Future concept.",
    enabledByDefault: false,
    routePrefixes: [],
  },
  {
    key: "projects.bimIfcUpload",
    label: "BIM IFC upload (in-app conversion)",
    group: "Project controls",
    description:
      "Let users upload a native IFC model in-app and convert it to XKT for viewing. Off by default while pre-baked XKT models are the supported path; enable to expose the Import model flow.",
    enabledByDefault: false,
    routePrefixes: [],
  },
  {
    key: "projects.selections",
    label: "Selections & allowances",
    group: "Project controls",
    description: "Homeowner finish/fixture selections with allowances, decisions and overage change requests.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/selections", "/project/:id/selections"],
  },
  {
    key: "projects.reporting",
    label: "Reporting",
    group: "Project controls",
    description: "PDF reports and reporting workflows.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/reporting", "/projects/:id/reports"],
  },
  {
    key: "projects.weather",
    label: "Weather intelligence",
    group: "Project controls",
    description: "Weather forecast, impact analysis and daily weather context.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/weather"],
  },
  {
    key: "project.team",
    label: "Team management",
    group: "Project controls",
    description: "On-site team members, roles, rates and site team tracking.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/team-members"],
  },
  {
    key: "quality.inspections",
    label: "Inspections",
    group: "Quality & risk",
    description: "Inspection requests, tracking and inspection reports.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/inspections"],
  },
  {
    key: "quality.dailyLogs",
    label: "Daily logs",
    group: "Quality & risk",
    description: "Daily site logs, entries, voiding and rich summaries.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/daily-logs"],
  },
  {
    key: "quality.risks",
    label: "Risk register",
    group: "Quality & risk",
    description: "Risk factors, scoring and mitigation tracking.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/risks", "/projects/:id/risk-factors"],
  },
  {
    key: "commercial.finances",
    label: "Project finances",
    group: "Commercial",
    description: "Finance summary, milestones, payments, disputes and escrow tracking.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/finances"],
  },
  {
    key: "commercial.budget",
    label: "Budget planning",
    group: "Commercial",
    description: "Budget categories, periods, allocations and budget planning pages.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/budget"],
  },
  {
    key: "commercial.invoices",
    label: "Invoices",
    group: "Commercial",
    description: "Invoice creation, overdue sweeps, payments and invoice lists.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/invoices"],
  },
  {
    key: "commercial.paymentClaims",
    label: "Payment claims",
    group: "Commercial",
    description: "Contractor progress claims / drawdowns against milestones, with an approval workflow.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/finances/payment-claims"],
  },
  {
    key: "commercial.purchaseOrders",
    label: "Purchase orders",
    group: "Commercial",
    description: "Vendor purchase orders with line items and committed-spend tracking.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/finances/purchase-orders"],
  },
  {
    key: "commercial.materialsEquipment",
    label: "Materials & equipment",
    group: "Commercial",
    description: "Material orders, BoQ import, equipment requests and procurement tracking.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/materials", "/projects/:id/equipment-requests", "/projects/:id/suppliers"],
  },
  {
    key: "commercial.materialsLedger",
    label: "Materials ledger",
    group: "Commercial",
    description: "Stock ledger, catalog, receipts, issues and adjustments.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/materials-ledger"],
  },
  {
    key: "commercial.transactions",
    label: "Transactions",
    group: "Commercial",
    description:
      "Photo-backed transaction ledger: record project expenses by category with optional receipt uploads, category breakdown charts and CSV export.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/transactions"],
  },
  {
    key: "collaboration.messaging",
    label: "Messaging",
    group: "Collaboration",
    description: "Project channels, real-time messaging and chat conversations.",
    enabledByDefault: true,
    routePrefixes: ["/channels", "/projects/:id/channels"],
  },
  {
    key: "collaboration.notifications",
    label: "Notifications",
    group: "Collaboration",
    description: "Notifications, preferences and notification email jobs.",
    enabledByDefault: true,
    routePrefixes: ["/notifications"],
  },
  {
    key: "collaboration.participants",
    label: "Client/homeowner participants",
    group: "Collaboration",
    description: "External stakeholders, homeowner access and project participant roles.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/participants"],
  },
  {
    key: "project.updates",
    label: "Project updates",
    group: "Collaboration",
    description: "Project announcements, update posts and milestone communications.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/updates"],
  },
  {
    key: "workflow.rfis",
    label: "RFIs",
    group: "Workflow",
    description: "RFIs, public RFI replies and reminders.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/rfis", "/rfi-reply"],
  },
  {
    key: "workflow.queries",
    label: "Queries",
    group: "Workflow",
    description: "Project queries and query responses.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/queries"],
  },
  {
    key: "workflow.approvals",
    label: "Approvals",
    group: "Workflow",
    description: "Approval requests, comments and approval decisions.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/approvals"],
  },
  {
    key: "workflow.changeRequests",
    label: "Change requests",
    group: "Workflow",
    description: "Change requests, budgets and client approvals.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/change-requests"],
  },
  {
    key: "workflow.actionItems",
    label: "Action items",
    group: "Workflow",
    description: "Action item tracking and reminders.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/action-items"],
  },
  {
    key: "compliance.permits",
    label: "Permits",
    group: "Compliance",
    description: "Permit register, expiry sweeps and permit reminders.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/permits"],
  },
  {
    key: "compliance.keyDates",
    label: "Key dates",
    group: "Compliance",
    description: "Contractual dates, reminders and date dashboards.",
    enabledByDefault: true,
    routePrefixes: ["/projects/:id/key-dates"],
  },
] as const satisfies readonly FeatureFlagDefinition[];

export type FeatureFlagKey = (typeof FEATURE_FLAGS)[number]["key"];
