/**
 * The starter roles a construction project is actually staffed with, as
 * additive participant grants, plus which side of the contract each sits on.
 *
 * These are not cosmetic labels over one checkbox set. Who answers an RFI, who
 * certifies a valuation, who signs an inspection off and who may never see the
 * contractor's costs all follow from the role and the side — which is why the
 * Resident Engineer is client-side even though they are on site every day, and
 * why the QS may price a change but not decide it.
 */

/** Additive capabilities granted to project participants (external stakeholders). */
export const PARTICIPANT_PERMISSIONS: Record<string, Record<string, readonly string[]>> = {
  // The employer. An inspection is a service they ORDER from BuildPanda, so
  // requesting one is theirs by right; they read the report and never write it.
  client: {
    project: ["view"],
    finances: ["view", "dispute"],
    approvals: ["view", "decide"],
    selections: ["view", "decide"],
    "change-requests": ["view"],
    stages: ["view"],
    buildings: ["view"],
    "key-dates": ["view"],
    comments: ["view", "post"],
    updates: ["view"],
    documents: ["view"],
    inspections: ["view", "request"],
    materials: ["view", "report"],
    contractors: ["view"],
    dailyLog: ["view", "report"],
    messages: ["view", "send"],
    participants: ["view"],
    teamMembers: ["view"],
    schedule: ["view"],
    rfis: ["view", "create"],
    bim: ["view"],
  },
  project_manager: {
    project: ["view"],
    tasks: ["view", "add", "remove"],
    finances: ["view", "viewCosts"],
    schedule: ["view", "manage"],
    documents: ["view", "upload"],
    inspections: ["view", "request", "manage"],
    materials: ["view", "manage", "report", "request"],
    contractors: ["view"],
    dailyLog: ["view", "create", "report"],
    updates: ["view", "post"],
    messages: ["view", "send"],
    comments: ["view", "post"],
    participants: ["view"],
    teamMembers: ["view"],
    stages: ["view"],
    buildings: ["view", "manage"],
    "key-dates": ["view", "manage"],
    rfis: ["view", "create", "respond", "manage"],
    approvals: ["view"],
    selections: ["view"],
    "change-requests": ["view", "manage"],
    permits: ["view", "manage"],
    risks: ["view", "manage"],
    bim: ["view", "upload"],
  },
  architect: {
    project: ["view"],
    tasks: ["view"],
    finances: ["view"],
    approvals: ["view"],
    selections: ["view"],
    "change-requests": ["view"],
    stages: ["view"],
    buildings: ["view"],
    "key-dates": ["view"],
    comments: ["view", "post"],
    updates: ["view"],
    documents: ["view"],
    inspections: ["view"],
    materials: ["view", "report"],
    contractors: ["view"],
    dailyLog: ["view", "report"],
    messages: ["view", "send"],
    participants: ["view"],
    teamMembers: ["view"],
    schedule: ["view"],
    rfis: ["view", "create", "respond"],
    bim: ["view"],
  },
  inspector: {
    project: ["view"],
    tasks: ["view"],
    finances: ["view"],
    approvals: ["view"],
    selections: ["view"],
    stages: ["view"],
    buildings: ["view"],
    "key-dates": ["view"],
    comments: ["view", "post"],
    updates: ["view"],
    documents: ["view"],
    inspections: ["view", "request"],
    materials: ["view", "report"],
    contractors: ["view"],
    dailyLog: ["view", "report"],
    participants: ["view"],
    schedule: ["view"],
    rfis: ["view"],
    bim: ["view"],
  },
  guest: {
    project: ["view"],
    tasks: ["view"],
    finances: ["view"],
    approvals: ["view"],
    selections: ["view"],
    updates: ["view"],
    documents: ["view"],
    inspections: ["view"],
    materials: ["view", "report"],
    contractors: ["view"],
    dailyLog: ["view", "report"],
    participants: ["view"],
    schedule: ["view"],
    stages: ["view"],
    buildings: ["view"],
    "key-dates": ["view"],
  },
  materials_requester: {
    project: ["view"],
    tasks: ["view"],
    approvals: ["view"],
    selections: ["view"],
    stages: ["view"],
    buildings: ["view"],
    "key-dates": ["view"],
    comments: ["view", "post"],
    updates: ["view"],
    documents: ["view"],
    inspections: ["view"],
    materials: ["view", "report", "request"],
    contractors: ["view"],
    dailyLog: ["view", "create", "report"],
    messages: ["view", "send"],
    participants: ["view"],
    teamMembers: ["view"],
    schedule: ["view"],
    rfis: ["view", "create"],
    bim: ["view"],
  },
  materials_approver: {
    project: ["view"],
    tasks: ["view"],
    approvals: ["view"],
    selections: ["view"],
    stages: ["view"],
    buildings: ["view"],
    "key-dates": ["view"],
    comments: ["view", "post"],
    updates: ["view"],
    documents: ["view"],
    inspections: ["view"],
    materials: ["view", "report", "request", "approve"],
    contractors: ["view"],
    dailyLog: ["view", "create", "report"],
    messages: ["view", "send"],
    participants: ["view"],
    teamMembers: ["view"],
    schedule: ["view"],
    rfis: ["view", "create"],
    bim: ["view"],
  },
  // The Engineer's Representative on a works contract: client-side, on site
  // every day. Answers RFIs, decides approvals, signs inspections off, and
  // reads the certificates submitted TO them — never the contractor's costs.
  resident_engineer: {
    project: ["view"],
    tasks: ["view"],
    finances: ["view"],
    approvals: ["view", "decide"],
    selections: ["view"],
    inspections: ["view", "request", "manage"],
    rfis: ["view", "create", "respond"],
    // Client-side: the Engineer's Representative DECIDES variations, they do
    // not raise them.
    "change-requests": ["view", "approve"],
    "key-dates": ["view"],
    stages: ["view"],
    buildings: ["view"],
    permits: ["view"],
    risks: ["view"],
    schedule: ["view"],
    documents: ["view"],
    materials: ["view", "report"],
    contractors: ["view"],
    dailyLog: ["view", "report"],
    updates: ["view"],
    comments: ["view", "post"],
    messages: ["view", "send"],
    participants: ["view"],
    bim: ["view"],
  },
  // Contractor-side commercial: prices the change, values the work, reads both
  // the certified position and the cost position.
  quantity_surveyor: {
    project: ["view"],
    tasks: ["view", "add", "remove"],
    finances: ["view", "viewCosts", "manage"],
    "change-requests": ["view", "manage"],
    stages: ["view", "manage"],
    buildings: ["view"],
    schedule: ["view"],
    "key-dates": ["view"],
    rfis: ["view", "create"],
    approvals: ["view"],
    selections: ["view"],
    materials: ["view", "report"],
    contractors: ["view"],
    documents: ["view", "upload"],
    dailyLog: ["view", "report"],
    updates: ["view"],
    comments: ["view", "post"],
    messages: ["view", "send"],
    participants: ["view"],
    permits: ["view"],
    risks: ["view"],
    bim: ["view"],
  },
  // Runs the site for the contractor: the programme, the diary, the orders.
  site_agent: {
    project: ["view"],
    tasks: ["view", "add", "remove"],
    finances: ["view", "viewCosts"],
    schedule: ["view", "manage"],
    stages: ["view", "manage"],
    buildings: ["view"],
    "key-dates": ["view", "manage"],
    dailyLog: ["view", "create", "void", "report"],
    materials: ["view", "report", "request"],
    inspections: ["view", "request"],
    rfis: ["view", "create", "respond"],
    "change-requests": ["view"],
    approvals: ["view"],
    selections: ["view"],
    permits: ["view", "manage"],
    risks: ["view", "manage"],
    documents: ["view", "upload"],
    contractors: ["view"],
    updates: ["view", "post"],
    comments: ["view", "post"],
    messages: ["view", "send"],
    participants: ["view"],
    bim: ["view"],
  },
  // Sets out and records what was built where; no commercial access at all.
  surveyor: {
    project: ["view"],
    tasks: ["view"],
    schedule: ["view"],
    stages: ["view"],
    buildings: ["view"],
    "key-dates": ["view"],
    dailyLog: ["view", "create", "report"],
    inspections: ["view", "request"],
    rfis: ["view", "create"],
    documents: ["view"],
    materials: ["view", "report"],
    updates: ["view", "post"],
    comments: ["view", "post"],
    messages: ["view", "send"],
    participants: ["view"],
    bim: ["view"],
  },
  // Gangs and plant on the day: the diary, the tasks, what to order.
  foreman: {
    project: ["view"],
    tasks: ["view", "add", "remove"],
    schedule: ["view"],
    stages: ["view"],
    buildings: ["view"],
    dailyLog: ["view", "create", "report"],
    materials: ["view", "report", "request"],
    inspections: ["view", "request"],
    rfis: ["view"],
    documents: ["view"],
    updates: ["view", "post"],
    comments: ["view", "post"],
    messages: ["view", "send"],
    participants: ["view"],
  },
  // Materials / lab engineer: approves what goes in the ground and records the
  // test certificates behind it.
  materials_engineer: {
    project: ["view"],
    tasks: ["view"],
    materials: ["view", "report", "request", "approve"],
    inspections: ["view", "request", "manage"],
    approvals: ["view", "decide"],
    dailyLog: ["view", "create", "report"],
    documents: ["view", "upload"],
    schedule: ["view"],
    stages: ["view"],
    buildings: ["view"],
    "key-dates": ["view"],
    rfis: ["view", "create"],
    updates: ["view"],
    comments: ["view", "post"],
    messages: ["view", "send"],
    participants: ["view"],
    contractors: ["view"],
  },
};

/**
 * Which side of the contract each starter role sits on. It decides who may be
 * ball-in-court on an RFI, who certifies a valuation and who signs an
 * inspection — a Resident Engineer is client-side even though they are on site
 * daily, and a QS is contractor-side even though they talk to the employer.
 */
export const ROLE_PRESET_SIDES: Record<string, "client" | "contractor" | "consultant"> = {
  client: "client",
  resident_engineer: "client",
  architect: "consultant",
  inspector: "consultant",
  materials_engineer: "consultant",
  project_manager: "contractor",
  quantity_surveyor: "contractor",
  site_agent: "contractor",
  surveyor: "contractor",
  foreman: "contractor",
  materials_requester: "contractor",
  materials_approver: "contractor",
  guest: "client",
};
