export const FEATURE_FLAGS = [
  "sales.leads",
  "sales.proposals",
  "ai.automatedTakeoff",
  "ai.programmeImport",
  "ai.projectFileImport",
  "ai.insights",
  "ai.chatAgent",
  "projects.documents",
  "projects.schedule",
  "projects.multiBuilding",
  "projects.bim",
  "projects.bimDashboard",
  "projects.bimIfcUpload",
  "projects.selections",
  "projects.reporting",
  "projects.weather",
  "project.team",
  "quality.inspections",
  "quality.dailyLogs",
  "quality.risks",
  "commercial.finances",
  "commercial.budget",
  "commercial.invoices",
  "commercial.paymentClaims",
  "commercial.purchaseOrders",
  "commercial.materialsEquipment",
  "commercial.materialsLedger",
  "commercial.transactions",
  "collaboration.messaging",
  "collaboration.notifications",
  "collaboration.participants",
  "project.updates",
  "workflow.rfis",
  "workflow.queries",
  "workflow.approvals",
  "workflow.changeRequests",
  "workflow.actionItems",
  "compliance.permits",
  "compliance.keyDates",
] as const;

export type FeatureFlagKey = (typeof FEATURE_FLAGS)[number];
