import * as XLSX from "xlsx";
import type { PricedLine } from "./classify.ts";
import type { ProjectMeta } from "./types.ts";

interface Row {
  [col: string]: string | number | null;
}

// Writes a priced BoQ in the Moniepoint sample layout:
// S/N | DESCRIPTION OF ITEM | QTY | UNIT | U/PRICE | AMOUNT, grouped by BESMM
// work section with per-section "to Summary" subtotals and a grand total.
export function writeBoqXlsx(
  lines: PricedLine[],
  project: ProjectMeta,
  outPath: string,
): { grandTotal: number; sections: number } {
  const aoa: Array<Array<string | number | null>> = [];
  const sym = project.currencySymbol;

  aoa.push([`BILL OF QUANTITIES — ${project.name}`]);
  aoa.push([`Location: ${project.location}`, "", "", "", `Currency:`, `${project.currency} (${sym})`]);
  aoa.push([`Generated by BuildPanda DWG→BoQ pipeline (BESMM4) — DRAFT for QS review`]);
  aoa.push([]);
  aoa.push(["S/N", "DESCRIPTION OF ITEM", "QTY", "UNIT", `U/PRICE (${sym})`, `AMOUNT (${sym})`, "CONFIDENCE"]);

  const bySection = new Map<string, PricedLine[]>();
  for (const l of lines) {
    const key = `${l.section}${l.sectionCode ? ` (${l.sectionCode})` : ""}`;
    const arr = bySection.get(key) ?? [];
    arr.push(l);
    bySection.set(key, arr);
  }

  let grandTotal = 0;
  let snBase = 0;
  for (const [section, sectionLines] of bySection) {
    aoa.push([]);
    aoa.push([section.toUpperCase()]);
    let sectionTotal = 0;
    sectionLines.forEach((l) => {
      const sn = String.fromCharCode(65 + (snBase % 26));
      snBase += 1;
      aoa.push([
        sn,
        l.description,
        l.quantity,
        l.unit,
        l.rate,
        l.amount,
        l.confidence,
      ]);
      if (l.amount) sectionTotal += l.amount;
    });
    aoa.push(["", `${section} to Summary:`, "", "", "", sectionTotal || null]);
    grandTotal += sectionTotal;
  }

  aoa.push([]);
  aoa.push(["", "GRAND TOTAL (Building Works)", "", "", "", grandTotal]);
  aoa.push([]);
  aoa.push(["NOTE: Quantities are AI-assisted take-offs from the DWG and assumptions; rates are seed values. A quantity surveyor MUST review before use."]);

  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws["!cols"] = [{ wch: 5 }, { wch: 52 }, { wch: 10 }, { wch: 7 }, { wch: 16 }, { wch: 18 }, { wch: 12 }];

  // Provenance sheet: full audit trail for every line.
  const prov: Array<Array<string | number | null>> = [["DESCRIPTION", "QTY", "UNIT", "BESMM SOURCE", "PROVENANCE / ASSUMPTIONS"]];
  for (const l of lines) prov.push([l.description, l.quantity, l.unit, l.besmmContext, l.provenance]);
  const wsProv = XLSX.utils.aoa_to_sheet(prov);
  wsProv["!cols"] = [{ wch: 46 }, { wch: 10 }, { wch: 7 }, { wch: 22 }, { wch: 90 }];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "BOQ");
  XLSX.utils.book_append_sheet(wb, wsProv, "Provenance");
  XLSX.writeFile(wb, outPath);

  return { grandTotal, sections: bySection.size };
}
